### ISSUE TITLE
Jugador solitario

### ISSUE THREAD

**Issue by oihanion** [GombocStudio/doors-monsters#36]
Te deja entrar en las partidas con un solo jugador en la sala aunque en las opciones ponga que haya 2, 3 o 4 jugadores.

Prioridad: baja

Para reproducir el error: Entrar o crear una sala, estar solo y darle a jugar.

**Comment by CesarMolto** [comment]
No se trata de un bug. El juego permite jugar solo por si se quieres prácticar estrategias sin tener a otros jugadores "molestando".
